name: hznb_ips
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  drop_down_list: ^2.0.0
  choice: ^2.3.2
  font_awesome_flutter: ^10.10.0
  flutter_launcher_icons: ^0.14.4
  mask_text_input_formatter: ^2.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3: ^2.9.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

 

flutter:
  uses-material-design: true

  assets:
    - images/datenbank_hinzu.png
    - images/hznb_logo_klein.png
    - icon/hznb_ico.png
    - database/pflegebericht.db3
